### ISSUE TITLE
Pass  all  workload file to   SFC experiments in cloudsimsdn not works 

### ISSUE THREAD

**Issue by shaker402** [Cloudslab/sfcwikiworkload#1]
This code generate. About 119 file.csv 
Wiki-Workload  

So I can't pass all these file to SFC experiments on cloudsimsdn 

Please help me how can I pass all this file as args: to eclipse

**Comment by hetianzhang** [comment]
Usage: [Policy] [SFCScale] [network topology file] [virtual topology file] [workload folder] [workload1] [workload2] [...]
```
LFF 0 your.physical.json your.virtual.json your-workload-folder/ 0_0_workload_wiki.csv 0_1_workload_wiki.csv ...
```
Please mind if your input workload is more than one, there is a space between the folder and the list of workload files. You can always modify the input of the example file anyway.

**Comment by hetianzhang** [comment]
For the workload list used in the argument, you can use some command to get, such as:
```
ls *.csv 
```

**Comment by shaker402** [comment]
> For the workload list used in the argument, you can use some command to get, such as:
> 
> ```
> ls *.csv 
> ```

Once again, I thank you dear very much thanks, appreciation and gratitud
